# Generated by Django 5.0.6 on 2024-07-03 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nameGenitive", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10)),
                ("scope", models.TextField(null=True)),
                ("compositionDate", models.DateField(null=True)),
                ("appointmentDate", models.DateField(null=True)),
                ("phone", models.CharField(max_length=20, null=True)),
                ("_type", models.CharField(max_length=20, null=True)),
                ("member_ids", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GuestSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("second_name", models.CharField(max_length=255, null=True)),
                ("family_name", models.CharField(max_length=255)),
                ("first_last_name", models.CharField(max_length=255)),
                ("birth_date", models.DateField(null=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PoliticalParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "number",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                ("prints_count", models.IntegerField()),
                ("prints_count_last_changed", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sitting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("date", models.DateField()),
                ("agenda", models.TextField()),
                ("closed", models.BooleanField()),
                ("remote", models.BooleanField()),
                ("jointWith", models.JSONField(default=list, null=True)),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search.committee",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.term"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_in_transcript", models.IntegerField()),
                (
                    "guest_speaker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search.guestspeaker",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search.mp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_in_statement", models.IntegerField()),
                ("text", models.TextField()),
                ("dense_vector", models.JSONField(null=True)),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search.committee",
                    ),
                ),
                (
                    "speaker_guest",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search.guestspeaker",
                    ),
                ),
                (
                    "speaker_mp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search.mp",
                    ),
                ),
                (
                    "sitting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.sitting"
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search.statement",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.term"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegislativeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.term"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommitteeTermMP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search.committee",
                    ),
                ),
                (
                    "mp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.mp"
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.term"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="committee",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="search.term"
            ),
        ),
        migrations.CreateModel(
            name="TermMP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mp_term_id", models.IntegerField()),
                (
                    "mp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.mp"
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.term"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "sitting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="search.sitting"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="statement",
            name="transcript",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="search.transcript"
            ),
        ),
        migrations.AddIndex(
            model_name="sitting",
            index=models.Index(fields=["date"], name="search_sitt_date_4bb860_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="sitting",
            unique_together={("committee", "term", "number")},
        ),
        migrations.AddIndex(
            model_name="paragraph",
            index=models.Index(
                fields=["place_in_statement"], name="search_para_place_i_cbfc9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paragraph",
            index=models.Index(
                fields=["statement"], name="search_para_stateme_2a9915_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paragraph",
            index=models.Index(
                fields=["speaker_mp"], name="search_para_speaker_e8b9bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paragraph",
            index=models.Index(
                fields=["committee"], name="search_para_committ_be5995_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="committeetermmp",
            unique_together={("committee", "term", "mp")},
        ),
        migrations.AlterUniqueTogether(
            name="termmp",
            unique_together={("mp_term_id", "term", "mp")},
        ),
        migrations.AddIndex(
            model_name="statement",
            index=models.Index(
                fields=["place_in_transcript"], name="search_stat_place_i_0a8f38_idx"
            ),
        ),
    ]
