# Generated by Django 5.0.6 on 2024-07-03 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mp",
            name="first_last_name",
        ),
    ]
